# Generated by Django 4.1.3 on 2023-01-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffinList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название гроба')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('content_details', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('slug', models.CharField(max_length=255, verbose_name='url Гроба')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Гробы',
                'verbose_name_plural': 'Гробы',
            },
        ),
    ]
